CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE logs (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OperationsType" integer NOT NULL,
    "Username" text NOT NULL,
    "IsUserAdmin" boolean NOT NULL,
    CONSTRAINT "PK_logs" PRIMARY KEY ("Id")
);

CREATE TABLE users (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Password" text NOT NULL,
    salt bytea NOT NULL,
    "isAdmin" boolean NOT NULL,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE books (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Author" text NOT NULL,
    "Description" text,
    "isAvailable" boolean NOT NULL,
    "UserId" integer,
    CONSTRAINT "PK_books" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_books_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id")
);

CREATE INDEX "IX_books_UserId" ON books ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240522090657_Initial', '8.0.5');

COMMIT;